djangoTest/urls.py
from django.conf.urls.defaults import patterns, include, url
from myBlog.views import postList,postDetail, userList, userPostList
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # call index.html, so in Angular can use ng-view
    url(r'^$', TemplateView.as_view(template_name="index.html")),
    url(r'^posts/$', postList.as_view(), name = 'post_list'),
    url(r'^posts/(?P<pk>[a-zA-Z0-9]+)/',postDetail.as_view(), name='post_detail'),#,{'template_name':'rest_framework/api_1.html'}),     

    url(r'^user/$', userList.as_view(), name='user_list'),
    url(r'user/(?P<name>[0-9a-zA-Z_+]+)/$',userList.as_view(),name='singel_user_list'),
    url(r'^user/(?P<name>[0-9a-zA-Z_-]+)/posts/$',userPostList.as_view(), name='user_post_list'),
    #url(r'^user/(?P<name>[0-9a-zA-Z_-]+)/posts/(?P<pk>[a-zA-Z0-9]+)/', postDetail.as_view(), name='user_post_detail'),
    
    # Examples:
    # url(r'^$', 'djangoTest.views.home', name='home'),
    # url(r'^djangoTest/', include('djangoTest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += patterns('', 
        url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')), )

djangoTest/myBlog/models.py
from django.db import models
# Create your models here.
from djangotoolbox.fields import ListField
from djangotoolbox.fields import EmbeddedModelField
from django_mongodb_engine.contrib import MongoDBManager
from django.contrib.auth.models import User

class Author(models.Model):
    #user = EmbeddedModelField(User)
    username = models.CharField(max_length=50)
    email = models.EmailField()
    #first_name = models.CharField(max_length=30)
    objects = MongoDBManager()   
    def __unicode__(self):
        return self.username
# Create your models here.
class Post(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=50)
    description = models.TextField(null=True)
    #if use id as foreignKey, then in the userPostList
    #it needs index to filter out related posts
    author = models.ForeignKey(User, related_name='posts')
    # mongo-django engine
    # use mongoDBManager then we can call method .raw_query() in views.
    objects = MongoDBManager()   
    def __unicode__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.description:
            self.description = self.title
        super(Post, self).save(*args, **kwargs)


      
#class User(models.User):'''

djangoTest/myBlog/views.py
# Create your views here.
from django.http import HttpResponse
from rest_framework import generics
from rest_framework import permissions
from djangoTest.myBlog.models import Post, Author
from serializer import postSerializer, authorSerializer,userPostSerializer,postDetailSerializer
from permissions import isOwnerOrReadOnly
from django.contrib.auth.models import User
'''
def createPost(request):
    #post = json.loads(request.raw_post_data)'''
'''Post(
         title = post['title'],
         description = post['description']
         ).save()
    posts = serializers.serialize('json', Post.objects.all()) 
    return HttpResponse('posts')
'''
class postList(generics.ListCreateAPIView):
    model = Post
    serializer_class = postDetailSerializer
    #comma!!!
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, isOwnerOrReadOnly)  
    def pre_save(self, obj):
        print self.request.user
        obj.author = self.request.user

class postDetail(generics.RetrieveUpdateDestroyAPIView):
    model = Post    
    serializer_class = postDetailSerializer
    #permission_classes = (permissions.IsAuthenticatedOrReadOnly, isOwnerOrReadOnly)

class userList(generics.ListAPIView):
    #use Author model here
    #use User model only for login
    model = User 
    #queryset = User.objects.all()
    serializer_class = authorSerializer
    #def get_queryset(self):
     #   return Author.objects.all()
    #lookup_filed = 'username'
   # def get_queryset(self):
    #    User.objects.raw_query()
    
class userPostList(generics.ListCreateAPIView):
    model = User
    serializer_class = userPostSerializer
    # filtering against URL like user/bob/posts
    def get_queryset(self):
        #get user name from URL 'name' group
        username = self.kwargs['name']
        #queryset = super(userPostList, self).get_queryset()
        print User.objects.filter(username=username)
        #raw_query is a method provided by mongo_django_engine
        #it's like a filter, only filter out certain author's posts
        return User.objects.filter(username=username)
class singelUserlist(userList):
    def get_queryset(self):
        username = self.kwargs['name']
        return User.objects.filter(username = username)
#class createUser():
'''
class userPostDetail(generics.ListAPIView):
    model = Post
    serializer_class = postSerializer
    def get_queryset(self):
        username = self.kwargs['name']
        pk = self.kwargs['pk']
        return Post.objects.filter(user__name=username)
'''
        

djangoTest/myBlog/templates/base.html
<!DOCTYPE html>
<!--Base html-->
<html lang="en" >
	<head>
			<script type="text/javascript" src="{{STATIC_URL}}angular/angular1-0-8.js"></script>
			<script type="text/javascript" src="{{STATIC_URL}}app.js"></script>
			<script type="text/javascript" src="{{STATIC_URL}}angular/angular-cookies.js"></script>
			<!--<script type="text/javascript" src="{{STATIC_URL}}angular/angular-resource.js"></script>-->
			<script type="text/javascript" src="{{STATIC_URL}}service.js"></script>
			<script type="text/javascript" src="{{STATIC_URL}}post-controller.js"></script>
			<script type="text/javascript" src="{{STATIC_URL}}post-service.js"></script>	
			
	</head>
</html>
<body ng-app="Blog">
	<p>start blocking</p>
{% block content %}
{% endblock %}
</body>

djangoTest/myBlog/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="{{STATIC_URL}}lib/jquery-1.10.2.js"></script>
    
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/fontello-71e14bde/css/fontello.css">
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/fontello-71e14bde/css/fontello-codes.css">
    <!-- Bootstrap -->
    <link href="{{STATIC_URL}}lib/bootstrap-3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="{{STATIC_URL}}lib/bootstrap-3.1.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/stylesheets/screen.css">
    <script type="text/javascript" src="{{STATIC_URL}}lib/angular-1.2.14/angular.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}lib/angular-1.2.14/angular-route.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}lib/angular-1.2.14/angular-animate.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}lib/angular-1.2.14/angular-cookies.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/app.js"></script>
	<!--<script type="text/javascript" src="{{STATIC_URL}}angular/angular-resource.js"></script>-->
	<script type="text/javascript" src="{{STATIC_URL}}js/post-controller.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/post-service.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}js/filters.js"></script>	

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
</html>
<!--index html in Templates folder -->
<body ng-app="Blog">
	<!--<p>start blocking</p>
	<a href='api-auth/login'>login</a>-->
	<div class=".container main">
		<div class="row title">
			<div class="col-md-8 col-md-offset-2">
				<div class="row"> 
					<div class="col-md-8">
						<h1><a href="#/">FlyAway</a></h1>
					</div>
					<div class="col-md-4 followLink">
						<h2> 
							<a href="https://www.facebook.com/guangyi.zhou.1" target="_blank"> <i class="icon-facebook"></i></a>
							<a href="https://twitter.com/Guangyi_flyaway" target="_blank"> <i class="icon-twitter"></i></a> 
							<a href="https://github.com/guangyi"> <i class="icon-github-circled"></i> </a>
						</h2> 
					</div>
				</div>
			</div>
		</div><!-- end of title-->
		<ng-view></ng-view>
</body>

	

djangoTest/myBlog/templates/myBlog/index.html
{% extends 'base.html' %}

{% block content %}
<p>Hello</p>
<ng-view view-state></ng-view>
{% endblock %}		
	<!--<script>
// Add the CSRF Token
var app = angular.module('Blog'); // Not including a list of dependent modules (2nd parameter to `module`) "re-opens" the module for additional configuration
app.config(['$httpProvider', function($httpProvider){
    $httpProvider.defaults.headers.common['X-CSRFToken'] = '{{ csrf_token|escapejs }}';
}]);
</script>-->

djangoTest/myBlog/templates/myBlog/post_list.html
<body ng-app="Blog">
	<div ng-controller="postCtrl">
		<label for="id_title">Title</label>
		<input type = "text" id="id_title" placeholder="Title" ng-model="post.title">
		<label for="id_description">description</label>
		<textarea type="text" id="id_description" ng-model="post.description"> </textarea>
		<button ng-click="create()">create</button>
		<!--Django's way to render a view
		{% for post in post_list %}
			<p>{{ post.title }}</p>
			<p>{{post.description}}</p>
		{% endfor %}-->
		<p>Hello{$ posts $}</p>
		<div ng-repeat="post in posts">
			<h2>{$ post.title $}</h2>
			<p>{$ post.description $}</p>
			<h3>{$ post.created_on $}</p>
		</div>
	</div>
</body>
	<!--<script>
// Add the CSRF Token
var app = angular.module('Blog'); // Not including a list of dependent modules (2nd parameter to `module`) "re-opens" the module for additional configuration
app.config(['$httpProvider', function($httpProvider){
    $httpProvider.defaults.headers.common['X-CSRFToken'] = '{{ csrf_token|escapejs }}';
}]);
</script>-->